import type { AppAnnouncementContent, MarketingCampaignContent } from '@/lib/email/types/email-template.types'

export const DEFAULT_ANNOUNCEMENT: AppAnnouncementContent = {
  campaignName:      'App Update',
  subject:           "What's new in Used Car Inspector AI",
  previewText:       'Discover the latest improvements to your AI car inspection experience.',
  eyebrow:           'App Update',
  headline:          "We've been busy improving your experience",
  subheadline:       'New features and improvements are now live.',
  introBody:         "We've been hard at work adding new features and polishing every corner of Used Car Inspector AI. Here's what's waiting for you.",
  ctaLabel:          "Explore What's New",
  ctaUrl:            'https://usedcarsdoctor.com',
  card1Icon:         '🔍',
  card1Title:        'Deeper VIN Analysis',
  card1Description:  'More data sources cross-checked for every inspection.',
  card2Icon:         '🛡️',
  card2Title:        'Enhanced Fraud Detection',
  card2Description:  'Smarter red flag identification across all listings.',
  card3Icon:         '📊',
  card3Title:        'Richer Reports',
  card3Description:  'More detail and clearer formatting in every report.',
  card4Icon:         '⚡',
  card4Title:        'Faster Processing',
  card4Description:  'Full inspection results delivered in seconds.',
  infoBlockTitle:    '',
  infoBlockBody:     '',
  secondaryTitle:    '',
  secondaryBody:     '',
  secondaryCtaLabel: '',
  secondaryCtaUrl:   '',
  footnote:          '',
  footerLinkLabel:   '',
  footerLinkUrl:     '',
  signatureLine:     '— The Used Cars Doctor Team',
}

export const DEFAULT_MARKETING_CAMPAIGN: MarketingCampaignContent = {
  campaignName:      'Marketing Campaign',
  subject:           'Know before you buy.',
  previewText:       'Most car buyers discover the problems after signing. Here\'s how to change that.',
  headline:          'Know exactly what you\'re buying before you sign.',
  introParagraph:    'Most used car buyers discover hidden problems days — or weeks — after they\'ve already handed over the money. Used Car Inspector AI changes that. Get VIN history, AI-powered photo analysis, and fraud detection in minutes, before you commit.',
  ctaLabel:          'Inspect a car for free →',
  ctaUrl:            'https://usedcarsdoctor.com',
  value1:            'Instant VIN history and accident record checks',
  value2:            'AI photo analysis that spots damage dealers hide',
  value3:            'Fraud detection that works before you meet the seller',
  trustParagraph:    'We\'ve helped buyers across Europe avoid expensive mistakes. Our reports have surfaced hidden accidents, odometer rollbacks, and title issues that sellers "forgot" to mention.',
  secondaryCtaLabel: 'See how it works',
  secondaryCtaUrl:   'https://usedcarsdoctor.com',
  footerNote:        'You\'re receiving this because you created an account with Used Car Inspector AI.',
}
